version: '3'

services:
    flaskapp:
        container_name: titda
        build: app
        restart: always
        ports:
            - '5001:5000'
        volumes:
            - ./app:/app
        networks:
            - backend

networks:
    backend:

volumes:
    app: